///////////////////////////////////////////////////////////////////
// AUTOGENERATED                                                 //
///////////////////////////////////////////////////////////////////

#pragma once

#include "components/matrix4.h"
#include "components/camera.h"
#include "components/soundassetref.h"
#include "components/vector3.h"
#include "components/player.h"
#include "components/world.h"
#include "components/quaternion.h"
#include "components/transform.h"
#include "components/textureassetref.h"
#include "components/meshassetref.h"
#include "components/objectid.h"
#include "components/skybox.h"
#include "components/vector2.h"
#include "components/hero.h"
#include "components/collider.h"
#include "components/sceneobject.h"
#include "components/scene.h"
