///////////////////////////////////////////////////////////////////
// AUTOGENERATED do not edit by hand                             //
///////////////////////////////////////////////////////////////////
#pragma once
#include "serializer.h"

struct SoundAssetRef {
  int id;

  void setDefaultValues() {
    std::memset(this, 0, sizeof(SoundAssetRef));
  }

  bool equals(const SoundAssetRef & rhs) const {
    return
      id == rhs.id;
  }
};

inline bool operator==(const SoundAssetRef &lhs, const SoundAssetRef &rhs) {
  return lhs.equals(rhs);
}

inline bool operator!=(const SoundAssetRef &lhs, const SoundAssetRef &rhs) {
  return !lhs.equals(rhs);
}

///////////////////////////////////////////////////////////////////
// serializer                                                    //
///////////////////////////////////////////////////////////////////
inline void serialize(SoundAssetRef &o, ISerializer &s) {
  s.begin();
  s.key("id");
  serialize(o.id, s);
  s.end();
}

///////////////////////////////////////////////////////////////////
// deserializer                                                  //
///////////////////////////////////////////////////////////////////
inline void deserialize(SoundAssetRef &o, IDeserializer &s) {
  o.setDefaultValues();
  while (s.next_key()) {
    switch (s.hash_key()) {
      case ros::hash("id"):
        deserialize(o.id, s);
        break;
      default: s.skip_key(); break;
    }
  }
}

///////////////////////////////////////////////////////////////////
// hashing                                                       //
///////////////////////////////////////////////////////////////////
namespace ros {
  inline ros::hash_value hash(SoundAssetRef &o) {
    ros::hash_value h = ros::hash(o.id);
    return h;
  }
}
