///////////////////////////////////////////////////////////////////
// AUTOGENERATED do not edit by hand                             //
///////////////////////////////////////////////////////////////////
#pragma once
#include "serializer.h"

struct World {
  ros::string<1024> title;
  ros::array<4, Player> player;
  ros::array<4, float> scores;

  void setDefaultValues() {
    std::memset(this, 0, sizeof(World));
    player.size = 0;
    scores.size = 0;
  }

  bool equals(const World & rhs) const {
    return
      player == rhs.player &&
      title == rhs.title &&
      scores == rhs.scores;
  }
};

inline bool operator==(const World &lhs, const World &rhs) {
  return lhs.equals(rhs);
}

inline bool operator!=(const World &lhs, const World &rhs) {
  return !lhs.equals(rhs);
}

///////////////////////////////////////////////////////////////////
// serializer                                                    //
///////////////////////////////////////////////////////////////////
inline void serialize(World &o, ISerializer &s) {
  s.begin();
  s.key("player");
  serialize(o.player, s);
  s.key("scores");
  serialize(o.scores, s);
  s.key("title");
  serialize(o.title, s);
  s.end();
}

///////////////////////////////////////////////////////////////////
// deserializer                                                  //
///////////////////////////////////////////////////////////////////
inline void deserialize(World &o, IDeserializer &s) {
  o.setDefaultValues();
  while (s.next_key()) {
    switch (s.hash_key()) {
      case ros::hash("player"):
        deserialize(o.player, s);
        break;
      case ros::hash("scores"):
        deserialize(o.scores, s);
        break;
      case ros::hash("title"):
        deserialize(o.title, s);
        break;
      default:
        s.skip_key();
        break;
    }
  }
}

///////////////////////////////////////////////////////////////////
// hashing                                                       //
///////////////////////////////////////////////////////////////////
namespace ros {
  inline ros::hash_value hash(World &o) {
    ros::hash_value h = ros::hash(o.player);
    h = ros::xor64(h);
    h ^= ros::hash(o.scores);
    return h;
  }
}
